apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ylz-xyz-ui-hpa-vvjp"
  namespace: "default"
  labels:
    app: "ylz-xyz-ui"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ylz-xyz-ui"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80