apiVersion: "v1"
kind: "Service"
metadata:
  name: "ylz-xyz-ui-service"
  namespace: "default"
  labels:
    app: "ylz-xyz-ui"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "ylz-xyz-ui"
  type: "LoadBalancer"
  loadBalancerIP: ""
